services:
  message-proxy:
    images: xxlgenius/message-proxy:1.0
    container_name: message-proxy
    restart: unless-stopped
    ports:
      - "8600:8000"
    environment:
      # 微信企业配置（必填）
      - wechat_copid=ww5829cfd5388f15ea
      - wechat_corpsecret=Q1UZcgGR2BIdu0UBZrj-90uaFItdsnoatPYtx4XCHZQ
      - wechat_agentid=1000002
      - app_token=PVveoC8sNjmXRF

    volumes:
      - ./logs:/app/logs
